'use server';

import { headers } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { createServiceClient } from '@/lib/supabase/service';
import { getViewer, FILE_BLOCKED_MESSAGES } from '@/lib/auth/viewer';
import { clientIp } from '@/lib/auth/fingerprint';
import { checkLimit, limitMessage } from '@/lib/rate-limit';
import { fileCaseSchema, fieldErrors, sanitizeText } from '@/lib/validation';
import { redact, rejectionMessage } from '@/lib/moderation/redact';
import { scanProfanity, SEVERE_MESSAGE } from '@/lib/moderation/profanity';
import { closeCaseIfDue } from '@/lib/court/gavel';
import {
  DEFAULT_PERSONA,
  PUBLIC_STATUSES,
  SESSION_HOURS,
  type CaseView,
  type Verdict,
  type VoteChoice,
  type JudgePersona,
  type CaseStatus,
} from '@/lib/types';
import type { Database } from '@/lib/supabase/database.types';

type CaseRow = Database['public']['Tables']['cases']['Row'];

export interface FileCaseResult {
  ok: boolean;
  /** `public_id` of the new case, e.g. "CASE-7501". Used to redirect. */
  publicId?: string;
  error?: string;
  fieldErrors?: Record<string, string>;
}

/**
 * Files a new case.
 *
 * Pipeline order is deliberate and must not be reordered:
 *   auth/tier → rate limit → Zod → redact (reject hard PII) → profanity →
 *   sanitize → insert
 *
 * Redaction runs before anything is persisted or sent to an LLM, so raw contact
 * details never leave this function.
 */
export async function fileCase(formData: FormData): Promise<FileCaseResult> {
  const viewer = await getViewer();

  // Gate 1 of 3 on the verified-only rule. RLS and `can_file_case()` are the
  // others — this one exists to produce a useful message.
  if (!viewer.canFile) {
    return {
      ok: false,
      error: viewer.fileBlockedReason
        ? FILE_BLOCKED_MESSAGES[viewer.fileBlockedReason]
        : 'You cannot file a case right now.',
    };
  }

  const ip = clientIp(await headers());
  const limit = await checkLimit('case:create', `${viewer.userId}:${ip}`);
  if (!limit.ok) return { ok: false, error: limitMessage(limit) };

  const parsed = fileCaseSchema.safeParse({
    category: formData.get('category'),
    title: formData.get('title'),
    body: formData.get('body'),
    persona: formData.get('persona') ?? DEFAULT_PERSONA,
    acceptedRules: formData.get('acceptedRules') === 'on',
  });
  if (!parsed.success) {
    return { ok: false, fieldErrors: fieldErrors(parsed.error) };
  }

  const { category, title, body, persona } = parsed.data;

  // Hard PII check across both fields. Rejecting beats silently redacting: the
  // author learns the rule instead of assuming it posted fine.
  const titleCheck = redact(title);
  const bodyCheck = redact(body);
  const rejections = [
    ...new Set([...titleCheck.rejections, ...bodyCheck.rejections]),
  ];
  if (rejections.length > 0) {
    return { ok: false, fieldErrors: { body: rejectionMessage(rejections) } };
  }

  const profanity = scanProfanity(`${title}\n${body}`);
  if (profanity.hasSevere) {
    return { ok: false, fieldErrors: { body: SEVERE_MESSAGE } };
  }

  const cleanTitle = sanitizeText(titleCheck.text);
  const cleanBody = sanitizeText(bodyCheck.text);

  // Sanitizing can shorten text; re-check the floor so an empty case can't slip in.
  if (cleanTitle.length < 8 || cleanBody.length < 60) {
    return {
      ok: false,
      fieldErrors: {
        body: 'That did not survive cleanup. Rewrite it as plain text.',
      },
    };
  }

  /*
   * Insert with the service client.
   *
   * `public_id` is generated by a DB default (a sequence), and `status` must be
   * set to 'live' — but `status` is a privileged column that the guard trigger
   * blocks for non-service roles. Authorisation has already been established
   * above via `viewer.canFile`, and `author_id` is taken from the verified
   * session rather than the form.
   *
   * A profanity hit does not block; it routes the case to `pending_review` so a
   * human sees it before the public does.
   */
  const admin = createServiceClient();
  const initialStatus: CaseStatus =
    profanity.hasProfanity || viewer.isShadowBanned ? 'pending_review' : 'live';

  /*
   * `public_id` is omitted deliberately: the DB default calls
   * `next_public_case_id()`, which removes any client-side race over case numbers.
   */
  const { data, error } = await admin
    .from('cases')
    .insert({
      author_id: viewer.userId!,
      category,
      title: cleanTitle,
      body: cleanBody,
      judge_persona: persona,
      status: initialStatus,
      language: 'en',
    })
    .select('public_id')
    .single();

  if (error) {
    console.error('[cases] insert failed:', error.message);
    return { ok: false, error: 'Could not file the case. Try again.' };
  }

  revalidatePath('/');
  return { ok: true, publicId: data.public_id };
}

// ── Reads ────────────────────────────────────────────────────────────────

/**
 * Assembles the verdict from its columns.
 *
 * Returns null unless the whole set is present: a half-written verdict would
 * render a broken card, so it is treated as absent.
 */
function readVerdict(row: CaseRow): Verdict | null {
  if (
    !row.ai_verdict ||
    !row.ai_verdict_line ||
    !row.ai_roast ||
    row.toxicity_score === null
  ) {
    return null;
  }

  return {
    verdict: row.ai_verdict,
    headline: row.ai_verdict_line,
    roast: row.ai_roast,
    summary: row.ai_summary ?? '',
    toxicity: row.toxicity_score,
  };
}

function toCaseView(
  row: CaseRow,
  viewerId: string | null,
  myVote: VoteChoice | null
): CaseView {
  // No `closes_at` column exists, so the deadline is derived once here rather
  // than recomputed in every component that needs a countdown.
  const closesAt = new Date(
    new Date(row.created_at).getTime() + SESSION_HOURS * 60 * 60 * 1000
  ).toISOString();

  return {
    id: row.id,
    publicId: row.public_id,
    category: row.category,
    title: row.title ?? 'Untitled case',
    body: row.body,
    status: row.status,
    createdAt: row.created_at,
    closedAt: row.closed_at,
    closesAt,
    redVotes: row.red_votes,
    greenVotes: row.green_votes,
    redWeight: row.red_weight,
    greenWeight: row.green_weight,
    verdict: readVerdict(row),
    toxicity: row.toxicity_score,
    persona: (row.judge_persona as JudgePersona) ?? DEFAULT_PERSONA,
    isSplitVerdict: row.is_split_verdict,
    isFeatured: row.is_featured,
    isAuthor: viewerId !== null && row.author_id === viewerId,
    myVote,
    isOpen: row.status === 'live' || row.status === 'judging',
    imageUrls: row.image_urls ?? [],
    mediaBlurred: row.media_blurred,
  };
}

const CASE_COLUMNS =
  'id, public_id, author_id, category, language, title, body, image_urls, ' +
  'red_votes, green_votes, red_weight, green_weight, status, judge_persona, ' +
  'judge_model, ai_verdict, ai_summary, ai_verdict_line, ai_roast, ai_reasoning, ' +
  'ai_confidence, toxicity_score, is_featured, is_sponsored, is_split_verdict, ' +
  'split_verdict_badge, media_blurred, report_count, verdict_attempts, heat, ' +
  'created_at, closed_at, updated_at';

/**
 * The docket feed: open cases first (they still need jurors), then recently
 * closed ones.
 *
 * Reads via the anon/user client so RLS applies. `pending_review`, `hidden` and
 * `deleted` are excluded explicitly rather than relying on policy alone.
 */
export async function getDocket(limit = 20): Promise<CaseView[]> {
  const supabase = await createClient();
  const viewer = await getViewer();

  const { data, error } = await supabase
    .from('cases')
    .select(CASE_COLUMNS)
    .in('status', PUBLIC_STATUSES)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (error) {
    console.error('[cases] docket query failed:', error.message);
    return [];
  }

  const rows = (data ?? []) as unknown as CaseRow[];

  // Open cases first — they are the ones that still need votes.
  rows.sort((a, b) => {
    const aOpen = a.status !== 'closed';
    const bOpen = b.status !== 'closed';
    if (aOpen !== bOpen) return aOpen ? -1 : 1;
    return b.created_at.localeCompare(a.created_at);
  });

  const votes = await getMyVotes(
    rows.map((r) => r.id),
    viewer.userId
  );
  return rows.map((row) =>
    toCaseView(row, viewer.userId, votes.get(row.id) ?? null)
  );
}

/** Today's Most Toxic: closed cases from the last 24h, ranked by heat. */
export async function getMostToxic(limit = 10): Promise<CaseView[]> {
  const supabase = await createClient();
  const viewer = await getViewer();
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();

  const { data, error } = await supabase
    .from('cases')
    .select(CASE_COLUMNS)
    .eq('status', 'closed')
    .gte('created_at', since)
    .order('heat', { ascending: false })
    .limit(limit);

  if (error) {
    console.error('[cases] toxic query failed:', error.message);
    return [];
  }

  const rows = (data ?? []) as unknown as CaseRow[];
  const votes = await getMyVotes(
    rows.map((r) => r.id),
    viewer.userId
  );
  return rows.map((row) =>
    toCaseView(row, viewer.userId, votes.get(row.id) ?? null)
  );
}

/**
 * A single case by `public_id`.
 *
 * Runs the lazy gavel first: if this case is past its deadline but the cron
 * hasn't swept it yet, close it now so the visitor never sees a frozen case.
 */
export async function getCase(publicId: string): Promise<CaseView | null> {
  await closeCaseIfDue(publicId);

  const supabase = await createClient();
  const viewer = await getViewer();

  const { data, error } = await supabase
    .from('cases')
    .select(CASE_COLUMNS)
    .eq('public_id', publicId)
    .in('status', PUBLIC_STATUSES)
    .maybeSingle();

  if (error || !data) return null;

  const row = data as unknown as CaseRow;
  const votes = await getMyVotes([row.id], viewer.userId);
  return toCaseView(row, viewer.userId, votes.get(row.id) ?? null);
}

/** The viewer's own ballots, so the UI can show which side they picked. */
async function getMyVotes(
  caseIds: string[],
  userId: string | null
): Promise<Map<string, VoteChoice>> {
  const result = new Map<string, VoteChoice>();
  if (!userId || caseIds.length === 0) return result;

  const supabase = await createClient();
  const { data } = await supabase
    .from('votes')
    .select('case_id, vote')
    .eq('user_id', userId)
    .in('case_id', caseIds);

  for (const row of data ?? []) {
    result.set(row.case_id, row.vote);
  }
  return result;
}

/** Public ids of closed cases, for the sitemap. */
export async function getClosedCaseIds(limit = 500): Promise<string[]> {
  const admin = createServiceClient();
  const { data } = await admin
    .from('cases')
    .select('public_id')
    .eq('status', 'closed')
    .order('created_at', { ascending: false })
    .limit(limit);

  return (data ?? []).map((row) => row.public_id);
}

/** Count of cases still taking votes, for the header badge. */
export async function getOpenCaseCount(): Promise<number> {
  const admin = createServiceClient();
  const { count } = await admin
    .from('cases')
    .select('id', { count: 'exact', head: true })
    .in('status', ['live', 'judging']);

  return count ?? 0;
}
