/**
 * Supabase schema types.
 *
 * Generated by hand from the live project's OpenAPI spec (`GET /rest/v1/`), so
 * these mirror the database as it actually exists rather than an idealised
 * schema. Regenerate properly with:
 *   npx supabase gen types typescript --project-id <id> > lib/supabase/database.types.ts
 *
 * Only the tables this app touches are typed. The project also contains
 * badges, boosts, follows, comments, notifications, referral_*, sponsored_slots
 * and grievance_cases, which are out of scope here.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ── Database enums ────────────────────────────────────────────────────────

export type CaseStatusDb =
  | 'pending_review'
  | 'live'
  | 'judging'
  | 'closed'
  | 'hidden'
  | 'deleted';

export type CaseCategoryDb =
  | 'dating'
  | 'friendship'
  | 'family'
  | 'work'
  | 'other';

export type VerdictTypeDb = 'red' | 'green' | 'split';
export type VoteTypeDb = 'red' | 'green';
export type LanguageDb = 'en' | 'hi';

export type ModerationActionDb =
  | 'warn'
  | 'cooldown_24h'
  | 'cooldown_7d'
  | 'ban'
  | 'content_hidden'
  | 'content_deleted';

export type AiJobTypeDb = 'moderator' | 'judge' | 'asr';
export type AiJobStatusDb = 'queued' | 'processing' | 'succeeded' | 'failed';

export interface Database {
  public: {
    Tables: {
      cases: {
        Row: {
          id: string;
          public_id: string;
          author_id: string | null;
          category: CaseCategoryDb;
          language: LanguageDb;
          title: string | null;
          body: string;
          image_urls: string[] | null;
          voice_url: string | null;
          voice_transcript: string | null;
          voice_duration_seconds: number | null;
          red_votes: number;
          green_votes: number;
          /** Tier-weighted tallies. Added by migration 002. */
          red_weight: number;
          green_weight: number;
          status: CaseStatusDb;
          judge_persona: string;
          judge_model: string | null;
          ai_verdict: VerdictTypeDb | null;
          ai_summary: string | null;
          ai_verdict_line: string | null;
          ai_roast: string | null;
          ai_reasoning: string | null;
          ai_confidence: number | null;
          ai_dissent: string | null;
          toxicity_score: number | null;
          is_featured: boolean;
          is_sponsored: boolean;
          sponsor_brand: string | null;
          sponsor_logo_url: string | null;
          toxic_of_day: string | null;
          is_split_verdict: boolean;
          split_verdict_badge: boolean;
          gdrive_synced_at: string | null;
          created_at: string;
          closed_at: string | null;
          updated_at: string;
          moderation_flags: string[] | null;
          media_blurred: boolean;
          tags: string[] | null;
          receipts: Json | null;
          witness_signals: Json | null;
          rebuttal: Json | null;
          verdict_version: number;
          amended_at: string | null;
          og_cache_url: string | null;
          og_cache_version: number;
          /** Report count, maintained by trigger. Added by migration 002. */
          report_count: number;
          /** Verdict attempt counter for the gavel. Added by migration 002. */
          verdict_attempts: number;
        };
        Insert: {
          id?: string;
          /** Defaults to `next_public_case_id()`; omit so Postgres assigns it. */
          public_id?: string;
          author_id?: string | null;
          category: CaseCategoryDb;
          language?: LanguageDb;
          title?: string | null;
          body: string;
          image_urls?: string[] | null;
          status?: CaseStatusDb;
          judge_persona?: string;
          tags?: string[] | null;
        };
        Update: {
          title?: string | null;
          body?: string;
          status?: CaseStatusDb;
          ai_verdict?: VerdictTypeDb | null;
          ai_summary?: string | null;
          ai_verdict_line?: string | null;
          ai_roast?: string | null;
          ai_reasoning?: string | null;
          ai_confidence?: number | null;
          toxicity_score?: number | null;
          judge_model?: string | null;
          is_split_verdict?: boolean;
          split_verdict_badge?: boolean;
          media_blurred?: boolean;
          moderation_flags?: string[] | null;
          closed_at?: string | null;
          updated_at?: string;
          report_count?: number;
          verdict_attempts?: number;
          og_cache_url?: string | null;
          og_cache_version?: number;
        };
        Relationships: [];
      };

      votes: {
        Row: {
          id: string;
          case_id: string;
          user_id: string;
          vote: VoteTypeDb;
          device_fingerprint: string | null;
          reason: string | null;
          idempotency_key: string | null;
          /** Tier weight this ballot carries. Added by migration 002. */
          weight: number;
          /** True for anonymous sessions; drives fingerprint dedupe. Migration 002. */
          is_anonymous_vote: boolean;
          created_at: string;
        };
        Insert: {
          case_id: string;
          user_id: string;
          vote: VoteTypeDb;
          device_fingerprint?: string | null;
          reason?: string | null;
          idempotency_key?: string | null;
          weight?: number;
          is_anonymous_vote?: boolean;
        };
        Update: {
          vote?: VoteTypeDb;
          weight?: number;
        };
        Relationships: [];
      };

      profiles: {
        Row: {
          id: string;
          handle: string;
          avatar_seed: string;
          karma: number;
          is_admin: boolean;
          is_pro: boolean;
          pro_expires_at: string | null;
          is_banned: boolean;
          ban_reason: string | null;
          is_shadow_banned: boolean;
          language: string;
          handle_changes_this_month: number;
          handle_changes_reset_at: string | null;
          jury_streak: number;
          jury_last_voted_on: string | null;
          free_boost_credits: number;
          grievance_sla_due_at: string | null;
          created_at: string;
          updated_at: string;
          /** Removed-case strikes. Added by migration 002. */
          strikes: number;
          /** Merchant-side Cashfree subscription reference. Migration 002. */
          cf_subscription_ref: string | null;
          cf_subscription_status: string | null;
        };
        Insert: {
          id: string;
          handle: string;
          avatar_seed: string;
          karma?: number;
          is_pro?: boolean;
          language?: string;
        };
        Update: {
          handle?: string;
          avatar_seed?: string;
          karma?: number;
          is_admin?: boolean;
          is_pro?: boolean;
          pro_expires_at?: string | null;
          is_banned?: boolean;
          ban_reason?: string | null;
          is_shadow_banned?: boolean;
          language?: string;
          jury_streak?: number;
          jury_last_voted_on?: string | null;
          strikes?: number;
          cf_subscription_ref?: string | null;
          cf_subscription_status?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };

      payments: {
        Row: {
          id: string;
          user_id: string | null;
          provider: string;
          cashfree_subscription_id: string | null;
          cashfree_plan_id: string | null;
          amount_inr: number | null;
          status: string;
          raw_event: Json | null;
          created_at: string;
          /** Webhook dedupe key. Added by migration 002 with a unique index. */
          event_id: string | null;
        };
        Insert: {
          user_id?: string | null;
          provider?: string;
          cashfree_subscription_id?: string | null;
          cashfree_plan_id?: string | null;
          amount_inr?: number | null;
          status: string;
          raw_event?: Json | null;
          event_id?: string | null;
        };
        Update: {
          status?: string;
          raw_event?: Json | null;
        };
        Relationships: [];
      };

      reports: {
        Row: {
          id: string;
          reporter_id: string | null;
          target_case_id: string | null;
          target_comment_id: string | null;
          reason: string;
          details: string | null;
          status: string;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          reporter_id?: string | null;
          target_case_id?: string | null;
          target_comment_id?: string | null;
          reason: string;
          details?: string | null;
          status?: string;
        };
        Update: {
          status?: string;
          resolved_at?: string | null;
        };
        Relationships: [];
      };

      moderation_logs: {
        Row: {
          id: string;
          target_type: string;
          target_id: string;
          target_user_id: string | null;
          action: ModerationActionDb;
          reason: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          target_type: string;
          target_id: string;
          target_user_id?: string | null;
          action: ModerationActionDb;
          reason?: string | null;
          metadata?: Json | null;
        };
        Update: never;
        Relationships: [];
      };

      admin_audit_logs: {
        Row: {
          id: string;
          admin_id: string | null;
          action: string;
          target_type: string;
          target_id: string;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          admin_id?: string | null;
          action: string;
          target_type: string;
          target_id: string;
          metadata?: Json | null;
        };
        Update: never;
        Relationships: [];
      };

      ai_jobs: {
        Row: {
          id: string;
          type: AiJobTypeDb;
          status: AiJobStatusDb;
          case_id: string | null;
          payload: Json | null;
          attempts: number;
          last_error: string | null;
          scheduled_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          type: AiJobTypeDb;
          status?: AiJobStatusDb;
          case_id?: string | null;
          payload?: Json | null;
          scheduled_at?: string;
        };
        Update: {
          status?: AiJobStatusDb;
          attempts?: number;
          last_error?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: {
      next_public_case_id: { Args: Record<never, never>; Returns: string };
    };
    Enums: {
      case_status: CaseStatusDb;
      case_category: CaseCategoryDb;
      verdict_type: VerdictTypeDb;
      vote_type: VoteTypeDb;
      moderation_action: ModerationActionDb;
      ai_job_type: AiJobTypeDb;
      ai_job_status: AiJobStatusDb;
    };
    CompositeTypes: Record<never, never>;
  };
}
